import type { Metadata } from "next";

export const metadata: Metadata = { title: "CV", description: "Experience, skills and education of Senior Product Designer Vladimir Deev-Kazanov." };

const roles = [
  { company: "Semrush", role: "Product Designer", date: "Feb 2024—Present", intro: "Leading product design for Local SEO tools that help small businesses manage their presence across platforms.", bullets: ["Sole designer for a four-week Google Business Profile AI Agent MVP, from onboarding and profile analysis through payment, dashboard, and settings.", "Designed trust boundaries for public-facing automation: narrated analysis, review-before-activation, and safe defaults.", "Measured the launch funnel directly with GA4 and SQL: 8% of landing-page visitors reached a configured dashboard in week one.", "Designed bulk location connection and Local product landing-page improvements linked internally to stronger retention and conversion."] },
  { company: "Raiffeisen Bank Russia", role: "Product Designer", date: "May 2019—Feb 2024", intro: "Designed high-stakes web and mobile banking workflows for entrepreneurs and relationship managers.", bullets: ["Led end-to-end design for account funding, self-service closure, QR payments, transaction search, and counterparty risk checks.", "A business-account top-up flow was associated with 70% fewer branch visits; self-service closure with 95% fewer support contacts.", "Designed a corporate CRM covering goals, portfolios, opportunities, tasks, and profitability.", "Ran the full cycle from research and flows through prototypes, usability testing, alignment, and implementation review."] }
];

export default function CV() { return <main className="cv-page shell">
  <section className="cv-hero"><p className="kicker">Curriculum vitae · 2026</p><h1>Vladimir<br />Deev-Kazanov</h1><div className="cv-intro"><h2>Senior Product Designer</h2><p>7+ years making complex AI and financial products understandable and trustworthy.</p><div><a href="mailto:vladimirdeev0@gmail.com">Email ↗</a><a href="tel:+35794091079">+357 940 910 79</a><a href="https://www.linkedin.com/in/vladimir-deev-kazanov-449a2459/">LinkedIn ↗</a></div></div></section>
  <section className="cv-block"><p className="kicker">Experience</p><div>{roles.map(r => <article className="role" key={r.company}><div className="role-title"><h2>{r.company}</h2><p>{r.role}<br/><span>{r.date}</span></p></div><p className="role-intro">{r.intro}</p><ul>{r.bullets.map(b => <li key={b}>{b}</li>)}</ul></article>)}</div></section>
  <section className="cv-block cv-columns"><div><p className="kicker">Skills</p><p className="large-list">Product design · Interaction design · AI product design · Human-in-the-loop workflows · Research · Analytics · Prototyping · Figma · UX writing</p></div><div><p className="kicker">Education</p><p><b>British Higher School of Art and Design</b><br/>UX/UI Design, 2018—2019</p><p><b>Higher School of Economics</b><br/>Digital Product Design, 2017—2018</p><p><b>Russian Foreign Trade Academy</b><br/>World Economy, 2007—2013</p><p className="kicker mini-gap">Languages</p><p>Russian — Native<br/>English — C1</p></div></section>
</main> }
