import type { Metadata } from "next";
import Arrow from "../Arrow";

export const metadata: Metadata = { title: "CV", description: "Experience, skills and education of Senior Product Designer Vladimir Deev-Kazanov." };

const roles = [
  { company: "Semrush", role: "Senior Product Designer", date: "Feb 2024—Present", intro: "Own product design for Local SEO initiatives serving small and multi-location businesses.", bullets: ["Redesigned Local product landing pages, increasing activation by 42% versus the previous version in the first month among visitors who were not existing Local SEO users; checked the result in Tableau.", "Served as sole designer for a four-week Google Business Profile AI Agent MVP, owning flows, UI, interaction decisions, default operating parameters, and engineering handoff with a product owner, two frontend engineers, two backend engineers, and QA.", "Made background automation legible through narrated analysis, visible completed and planned work, configuration before activation, and adjustable cadence. To meet the launch deadline, the MVP shipped without in-product recovery for incorrectly published content.", "With no analyst on the team, measured the launch funnel using GA4 and SQL: 8% of landing-page visitors reached the configured agent dashboard during the initial measurement period. Treated the result as directional because there was no baseline, target, or absolute sample size."] },
  { company: "Raiffeisen Bank Russia", role: "Senior Product Designer", date: "May 2019—Feb 2024", intro: "Designed complex web and mobile banking products for entrepreneurs and an enterprise CRM for CIB teams.", bullets: ["Led end-to-end design for account funding, self-service account closure, QR payments, transaction search, and counterparty risk assessment across web and mobile banking.", "Tested QR-payment prototypes with five entrepreneur customers. After redesigning unclear Central Bank terminology and adding a choice page, reusable QR creation increased 17% in the first month; a backend engineer supplied the production count at my request.", "Designed an account top-up flow associated with 70% fewer branch visits and a self-service account-closure flow associated with 95% fewer support contacts. The product owner supplied both results; I did not have direct analytics access.", "Designed a corporate CRM covering goals, client portfolios, profitability, product opportunities, tasks, meetings, and activity history for relationship managers and team leads."] }
];

export default function CV() { return <main id="main-content" className="cv-page shell">
  <section className="cv-hero"><p className="kicker">Curriculum vitae · 2026</p><h1>Vladimir<br />Deev-Kazanov</h1><div className="cv-intro"><h2>Senior Product Designer</h2><p>7+ years designing complex B2B SaaS and fintech workflows across web and mobile—combining user research, interaction design, AI automation, and product analytics to take ambiguous problems through to shipped outcomes.</p><div><a href="mailto:vladimirdeev0@gmail.com" data-analytics-event="contact_email">Email<Arrow /></a><a href="https://www.linkedin.com/in/vladimir-deev-kazanov/" target="_blank" rel="noreferrer" aria-label="LinkedIn (opens in new tab)" data-analytics-event="contact_linkedin">LinkedIn<Arrow /></a><a href="https://www.dropbox.com/scl/fi/btau8m3m8eyx33bucfbwr/vladimir-deev-kazanov-senior-product-designer-cv.pdf?rlkey=ygjysv656sy6on79zhyumi8d5&st=ubjxd80o&dl=1" target="_blank" rel="noreferrer" aria-label="Download CV (opens in new tab)" data-analytics-event="cv_download">Download CV<Arrow /></a></div></div></section>
  <section className="cv-block"><p className="kicker">Experience</p><div>{roles.map(r => <article className="role" key={r.company}><div className="role-title"><h2>{r.company}</h2><p>{r.role}<br/><span>{r.date}</span></p></div><p className="role-intro">{r.intro}</p><ul>{r.bullets.map(b => <li key={b}>{b}</li>)}</ul></article>)}</div></section>
  <section className="cv-block cv-columns"><div><p className="kicker">Skills</p><p className="large-list">Complex B2B workflows · AI automation / human-in-the-loop · Interaction design · Product analytics / experimentation · User research · Fintech · Figma / FigJam · Tableau / GA4 / SQL · Rapid prototyping</p></div><div><p className="kicker">Education</p><p><b>British Higher School of Art and Design</b><br/>UX/UI Design, 2018—2019</p><p><b>Higher School of Economics</b><br/>Digital Product Design, 2017—2018</p><p><b>Russian Foreign Trade Academy</b><br/>World Economy Specialist, International Business / Trade / Commerce, 2007—2013</p><p className="kicker mini-gap">Certification</p><p><b>GoPractice, Inc.</b><br/>Data-driven Product Management Simulator</p><p className="kicker mini-gap">Languages</p><p>Russian — Native<br/>English — C1 / Professional working proficiency</p></div></section>
</main> }
