import type { Metadata } from "next";

export const metadata: Metadata = { title: "CV", description: "Experience, skills and education of Senior Product Designer Vladimir Deev-Kazanov." };

const roles = [
  { company: "Semrush", role: "Product Designer", date: "Feb 2024—Present", intro: "Lead product design for Local SEO tools that help small businesses manage listings and keep their Google Business Profile information accurate across platforms.", bullets: ["Served as sole designer for a four-week Google Business Profile AI Agent MVP, owning flows, UI, interaction decisions, default operating parameters, and engineering handoff across onboarding, profile analysis, payment, review, dashboard, and settings.", "Designed trust boundaries for public-facing automation: narrated profile analysis, review before activation, and positive-only automatic review replies by default.", "Partnered with a product owner, two frontend engineers, two backend engineers, and QA; shared responsibility for MVP scope and launch criteria. Agent architecture, model behaviour, pricing, and landing-page copy were outside my ownership.", "Measured the launch funnel using GA4 and SQL: 8% of landing-page visitors reached the dashboard in week one. The result is directional because there was no prior baseline or target and access permission preceded personalised value.", "Designed a bulk location-connection flow reported internally to improve MRR and retention, and redesigned Local product landing pages reported to increase CTA conversion; exact figures are unavailable."] },
  { company: "Raiffeisen Bank Russia", role: "Product Designer", date: "May 2019—Feb 2024", intro: "Designed high-stakes web and mobile banking workflows for entrepreneurs and a corporate CRM for relationship managers.", bullets: ["Led end-to-end design for business-account funding, self-service account closure, QR-code payments, transaction search, and counterparty risk checks.", "Designed a business-account top-up flow associated with 70% fewer branch visits and a self-service account-closure flow associated with 95% fewer support contacts. The results were provided by the product owner after launch; I did not have direct analytics access.", "Designed a corporate CRM for CIB relationship managers and product sales teams, covering goals, client portfolios, product opportunities, tasks, and profitability.", "Ran the full design cycle from requirements and user research through flows, prototypes, usability testing, stakeholder alignment, and implementation review."] }
];

export default function CV() { return <main id="main-content" className="cv-page shell">
  <section className="cv-hero"><p className="kicker">Curriculum vitae · 2026</p><h1>Vladimir<br />Deev-Kazanov</h1><div className="cv-intro"><h2>Senior Product Designer</h2><p>7+ years making complex marketing SaaS and financial products understandable and trustworthy.</p><div><a href="mailto:vladimirdeev0@gmail.com">Email ↗</a><a href="https://www.linkedin.com/in/vladimir-deev-kazanov-449a2459/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://www.behance.net/gallery/157977921/Vova-Deev-Kazanov" target="_blank" rel="noreferrer">Behance ↗</a></div></div></section>
  <section className="cv-block"><p className="kicker">Experience</p><div>{roles.map(r => <article className="role" key={r.company}><div className="role-title"><h2>{r.company}</h2><p>{r.role}<br/><span>{r.date}</span></p></div><p className="role-intro">{r.intro}</p><ul>{r.bullets.map(b => <li key={b}>{b}</li>)}</ul></article>)}</div></section>
  <section className="cv-block cv-columns"><div><p className="kicker">Skills</p><p className="large-list">Product design · Interaction design · Marketing SaaS · AI product design · Human-in-the-loop workflows · User research · Usability testing · JTBD · Product analytics · Prototyping · Figma · UX writing · Web and mobile applications</p></div><div><p className="kicker">Education</p><p><b>British Higher School of Art and Design</b><br/>UX/UI Design, 2018—2019</p><p><b>Higher School of Economics</b><br/>Design and Development of Digital Products, 2017—2018</p><p><b>Russian Foreign Trade Academy</b><br/>World Economy Specialist, International Business / Trade / Commerce, 2007—2013</p><p className="kicker mini-gap">Certification</p><p><b>GoPractice, Inc.</b><br/>Data-driven Product Management Simulator</p><p className="kicker mini-gap">Languages</p><p>Russian — Native<br/>English — C1 / Professional working proficiency</p></div></section>
</main> }
